version: "3"

x-minio-common: &minio-common
  image: minio/minio
  command: server http://minio{1...2}/data{1...2} --console-address ":9001"
  environment:
    MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
    MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  expose:
    - "9000"
    - "9001"

services:
  minio1:
    <<: *minio-common
    hostname: minio1

  minio2:
    <<: *minio-common
    hostname: minio2

  nginx:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
