version: "3"

services:
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "9000:9000"
