name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: build-${{ matrix.deno-version == 'nightly' && 'nightly' || 'release' }}-${{ matrix.unstable && 'unstable' || 'stable' }}-${{ matrix.no-check && 'nocheck' || 'tsc' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v1.x, nightly]
        unstable: [false, true]
        no-check: [false, true]
    env:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    steps:
      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno-version }}

      - uses: actions/checkout@v2

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable

      - name: Setup Tests
        run: docker-compose up -d

      - name: Test
        run: make test DENO_ARGS="${{ matrix.unstable && ' --unstable' || '' }}${{ matrix.no-check && ' --no-check' || '' }}"

      - name: Cleanup
        run: make cleanup
