name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: build-${{ matrix.deno-version == 'nightly' && 'nightly' || 'release' }}-${{ matrix.unstable && 'unstable' || 'stable' }}-${{ matrix.no-check && 'nocheck' || 'tsc' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v1.4.0, nightly]
        unstable: [false, true]
        no-check: [false, true]
    env:
      AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
      AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    steps:
      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: v1.3.3

      - uses: actions/checkout@v2

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint --unstable

      - name: Start minio
        run: |
          docker-compose up -d
          aws --endpoint-url "http://localhost:9000" s3 mb s3://test

      - name: Test
        run: deno test --allow-net --allow-env${{ matrix.unstable && ' --unstable' || '' }}${{ matrix.no-check && ' --no-check' || '' }}
